### PR TITLE
Upgrade to play 2.6

### PR DESCRIPTION
**Pull request by akitaylor**
Hi!

I've made a trial to upgrade to play 2.6, please review if it is OK. All test are running fine.

Regards,
Akos

### CODE REVIEW

**Review by muuki88 — APPROVED** [review]
Thanks for taking the time to upgrade to play 2.6 :)

**Comment by akitaylor** [comment]
I'm happy to contribute ;-) When do you expect to publish the new release?

**Comment by muuki88** [comment]
Great to hear 😍
Releasing is done by @jroper

**Comment by cconstantin** [comment]
Hello everyone. Any updates on when this will be released? Thanks!

**Comment by jroper** [comment]
I've released version 1.5.0. Please note, the package name/deployment location has changed, see https://github.com/jroper/play-geojson#150-migration-notes for details.

**Comment by cconstantin** [comment]
Thanks @jroper . I've submitted a PR to correct the group id in the migration notes.

**Pull request merged**
